- name: убеждаемся, что директрия существует
  ansible.builtin.file:
    path: "/home/{{ user_name }}/monitoring"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'


- name: копируем файлы для мониторинга
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'
  loop:
    - { src: 'compose.yml', dest: '/home/{{ user_name }}/monitoring/compose.yml' }
    - { src: '.env', dest: '/home/{{ user_name }}/monitoring/.env' }

- name: Запускаем контейнер с помощью docker-compose
  community.docker.docker_compose_v2:
    project_src: /home/{{ user_name }}/monitoring
    state: present
    pull: missing
