filebeat.inputs:
  # Читаем абсолютно всё из системного журнала (включая систему и докер)
  - type: journald
    id: all-logs


output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"

setup.kibana:
  host: "http://kibana:5601"