- name: создаем директорию для web-приложения
  ansible.builtin.file:
    path: /home/{{ user_name }}/app 
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'


- name: копируем файлы для web-приложения
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: /home/{{ user_name }}/app/index.html
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'