- name: создаем директорию для мониторинга
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'
  loop:
    - "/home/{{ user_name }}/monitoring"
    - "/home/{{ user_name }}/monitoring/prometheus"


- name: копируем файлы для мониторинга
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'
  loop:
    - { src: 'prometheus.yml', dest: '/home/{{ user_name }}/monitoring/prometheus/prometheus.yml' }